services:

  back:
    image: fiftyfifty-backend
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: backend
    env_file:
      - ./back/.env
    volumes:
      - ./back/src:/app/src
    ports:
      - 3000:3000

  front:
    image: fiftyfifty-frontend
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./front/src:/app/src
    ports:
      - 3001:3001

  database:
    image: postgres:15-bookworm
    ports:
      - ${FIFTY_POSTGRES_PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${FIFTY_DB:-fifty} -U ${FIFTY_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${FIFTY_USER:-postgres}
      POSTGRES_DB: ${FIFTY_DB:-fifty}
      POSTGRES_PASSWORD: ${FIFTY_PASS:-secret}
    volumes:
      - db_data:/var/lib/postgresql/data

  migrater:
    image: fiftyfifty-backend
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: ["sh", "-c", "npx node-pg-migrate up"]
    depends_on:
      database:
        condition: service_healthy
    container_name: migrater
    environment:
      DATABASE_URL: postgres://postgres:secret@database:5432/fifty
    volumes:
      - ./back/src:/app/src
      - ./back/migrations:/app/migrations

volumes:
  db_data:
